import { ReactNode } from "react";
import "./globals.css";
import { Lato } from "next/font/google";

// components
import Navbar from "./components/Navbar";

const lato = Lato({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
